version: 2

models:
  - name: issues
    description: Cleaned Jira issues
    columns:
      - name: issue_id
        tests: [not_null]
      - name: issue_key
        tests: [not_null]

  - name: sprints
    description: Cleaned Jira sprints
    columns:
      - name: sprint_id
        tests: [not_null]